version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    container_name: ${POSTGRES_DOCKER_CONTAINER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${HOST_PORT}:${cONTAINER_PORT}"
    volumes:
      - ./:/bootcamp/
      - ./data.dump:/docker-entrypoint-initdb.d/data.dump
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: on-failure
    env_file:
      - .env
    container_name: ${PGADMIN_DOCKER_CONTAINER}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

#if the volumes and not defined as below, Docker Compose can't create them automatically
# and will throw an error when trying to start the services.
volumes:
  postgres_data:
  pgadmin_data:
